########################
######README#########
########################
# docker container run -d --name loadbalancer -p 80:80 -v $(pwd):/usr/share/nginx/html nginx

# this will start nginx and use my local drive as a bind mount to /usr/share/nginx/html on the container
# this essentially means both host and container share the index.html file 

FROM nginx:latest

