#### Docker-compose file used to create a drupal site with a postgres backend

## Add the secret to the swarm cluster
# echo "IAmSecure" | docker secret create psql-pw -
## deploy the service
# docker stacks deploy -c docker-compose.yml psql1

version: "3.7"
services: 
  
    drupal:
        image: drupal:8.2
        ports:
            - "8080:80"
        volumes: 
            - type: volume
              source: drupal-sites-temp
              target: /temporary/sites
            - type: volume
              source: drupal-modules
              target: /var/www/html/modules
            - type: volume
              source: drupal-profiles
              target: /var/www/html/profiles
            - type: volume
              source: drupal-sites
              target: /var/www/html/sites
            - type: volume
              source: drupal-themes
              target: /var/www/html/themes

    postgresdb:
        image: postgres:12.2
        environment: 
            POSTGRES_PASSWORD_FILE: /run/secrets/psql-pw
        volumes: 
            - type: volume
              source: pgsqlvolume
              target: /var/lib/postgresql/data
        secrets:
            - psql-pw

volumes: 
    pgsqlvolume:
    drupal-themes:
    drupal-sites:
    drupal-profiles:
    drupal-sites-temp:
    drupal-modules:

secrets:
    psql-pw:
        external: true