#Run this locally (Not in a swarm) and it will add secrets into the container as bind mounts
# (It literally mounts ./psql_user.txt as a BIND MOUNT to /run/secrets/psql_user)
version: "3.1"

services:
  psql:
    image: postgres
    secrets:
      - psql_user
      - psql_password
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/psql_password
      POSTGRES_USER_FILE: /run/secrets/psql_user

secrets:
  psql_user:
    file: ./psql_user.txt
  psql_password:
    file: ./psql_password.txt

