### Deploy with:
  # kubectl apply -f app.yml
  # kubectl get deployment
  # kubectl get service
  # kubectl get pod
  # kubectl describe service app-nginx-service
  # kubectl run --generator=run-pod/v1 tmp-shell --rm -it --image=bretfisher/netshoot -- bash
  # curl app-nginx-service
apiVersion: v1
kind: Service
metadata:
  name: app-nginx-service
  labels:
    app: nginx-1
spec:
  type: NodePort
  ports:
  - port: 80
  # The selector is essentially the label to match the service too
  # See below the Deployment with a label of app-nginx
  selector:
    app: app-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-nginx
  template:
    metadata:
      labels:
        app: app-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.17.3
        ports:
        - containerPort: 80
