version: "3.7"

services:
  web:
    image: steveyttt/healthchecknginx
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost"]
        interval: 30s
        timeout: 30s
        retries: 3
        start_period: 20s